<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;
use Illuminate\Validation\Rule;

class UpsertServicePageSectionsRequest extends FormRequest
{
    public const SECTION_KEYS = [
        'how_we_work',
        'who_is_this_for',
        'real_results_delivered',
        'client_testimonials',
        'frequently_asked_questions',
        'technologies_we_use',
        'what_you_get',
        'why_choose_our_service',
        'hero',
        'cta',
        'stats',
        'benefits',
        'faq',
        'overview',
        'seo',
        'highlights',
        'related',
        'solutions',
        'industries',
        'tools',
        'blogs',
        'free-tools',
        'comparisons',
        'case-studies',
        'featured',
        'directory',
        // new modules keys
        'header',
        'whyus',
        'comparison',
        'process',
        'result',
        'review',
        'techspec',
        'data',
        'delivered',
        'usecase',
        'results',
    ];

    public function authorize(): bool
    {
        return true;
    }

    public function rules(): array
    {
        return [
            'locale' => ['nullable', 'string', 'max:16', 'regex:/^[a-z]{2}(-[A-Z]{2})?$/'],
            'sections' => ['required', 'array', 'min:1', 'max:15'],
            'sections.*.section_key' => ['required', 'distinct', Rule::in(self::SECTION_KEYS)],
            'sections.*.heading' => ['nullable', 'string', 'max:255'],
            'sections.*.subheading' => ['nullable', 'string', 'max:1200'],
            'sections.*.is_active' => ['nullable', 'boolean'],
            'sections.*.items' => ['required', 'array', 'max:100'],
            'sections.*.items.*' => ['nullable', 'array'],
            'sections.*.items.*.title' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.description' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.value' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.question' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.answer' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.name' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.role' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.quote' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.metric' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.author_name' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.author_title' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.company' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.content' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.rating' => ['nullable', 'integer', 'min:1', 'max:5'],
            'sections.*.items.*.category' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.results' => ['nullable', 'array'],
            'sections.*.items.*.results.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.technologies' => ['nullable', 'array'],
            'sections.*.items.*.technologies.*' => ['nullable', 'string', 'max:100'],
            'sections.*.items.*.icon' => ['nullable', 'string', 'max:100'],
            'sections.*.items.*.number' => ['nullable', 'string', 'max:20'],
            'sections.*.items.*.project_url' => ['nullable', 'url', 'max:255'],
            
            // New Catalog and Directory Item properties
            'sections.*.items.*.tag' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.heading' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.subheading' => ['nullable', 'string', 'max:1200'],
            'sections.*.items.*.subtext' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.badge' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.href' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.slug' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.date' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.excerpt' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.featured' => ['nullable', 'boolean'],
            'sections.*.items.*.is_featured' => ['nullable', 'boolean'],
            'sections.*.items.*.status' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.tags' => ['nullable', 'array'],
            'sections.*.items.*.tags.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.keywords' => ['nullable', 'array'],
            'sections.*.items.*.keywords.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.image' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.path' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.comparison' => ['nullable', 'array'],
            'sections.*.items.*.comparison.leftHeading' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.comparison.rightHeading' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.comparison.leftPoints' => ['nullable', 'array'],
            'sections.*.items.*.comparison.leftPoints.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.comparison.rightPoints' => ['nullable', 'array'],
            'sections.*.items.*.comparison.rightPoints.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.preview' => ['nullable', 'array'],
            'sections.*.items.*.preview.text' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.preview.url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.full' => ['nullable', 'array'],
            'sections.*.items.*.full.description' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.full.text' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.full.url' => ['nullable', 'string', 'max:2000'],
            
            // Missing frontend page item properties
            'sections.*.items.*.url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.duration' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.timeline' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.cta_preview_text' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.cta_preview_url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.cta_full_description' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.cta_full_text' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.cta_full_url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.preview_text' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.preview_url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.full_text' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.full_description' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.full_url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.leftHeading' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.rightHeading' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.leftPoints' => ['nullable', 'array'],
            'sections.*.items.*.leftPoints.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.rightPoints' => ['nullable', 'array'],
            'sections.*.items.*.rightPoints.*' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.align' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.photo_url' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.variant' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.techtag' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.techHeading1' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.techHeading2' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.techSubtext' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.techTagsText' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.tagsText' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.resultsText' => ['nullable', 'string', 'max:2000'],
            'sections.*.items.*.title1' => ['nullable', 'string', 'max:255'],
            'sections.*.items.*.title2' => ['nullable', 'string', 'max:255'],
            'publish' => ['nullable', 'boolean'],
        ];
    }
}
